<section class="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6">
@include('partials.settings-heading')
<x-settings.layout :heading="__('Update password')" :subheading="__('Keep your account protected with a strong password')">
<form wire:submit="updatePassword" class="mt-6 grid gap-5"><x-ui.input wire:model="current_password" label="Current password" type="password" required autocomplete="current-password"/><x-ui.input wire:model="password" label="New password" type="password" required autocomplete="new-password"/><x-ui.input wire:model="password_confirmation" label="Confirm password" type="password" required autocomplete="new-password"/><x-ui.button type="submit" class="w-fit" data-test="update-password-button">Save</x-ui.button></form>

@if($canManageTwoFactor)
<section class="mt-12 border-t border-slate-200 pt-8 dark:border-slate-700"><h3 class="text-lg font-bold">Two-factor authentication</h3><p class="mt-1 text-sm text-slate-600 dark:text-slate-300">Manage your two-factor authentication settings</p>
<div class="mt-5">@if($twoFactorEnabled)<p class="mb-4 text-sm">Your account requires a secure authenticator code during login.</p><x-ui.button variant="danger" wire:click="disable">Disable 2FA</x-ui.button><livewire:settings.two-factor.recovery-codes :$requiresConfirmation/>@else<p class="mb-4 text-sm text-slate-600">Add an authenticator app for stronger account security.</p><x-ui.button wire:click="enable">Enable 2FA</x-ui.button>@endif</div>
<div x-cloak x-show="$wire.showModal" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><div class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900">
<div class="flex justify-between gap-4"><div><h3 class="text-xl font-bold">Set up two-factor authentication</h3><p class="mt-1 text-sm text-slate-600">Scan the code or enter the setup key.</p></div><button type="button" wire:click="closeModal" aria-label="Close">✕</button></div>
@if($showVerificationStep)<div class="mt-6 grid gap-4"><x-ui.input wire:model="code" label="Six-digit authentication code" inputmode="numeric" maxlength="6"/><div class="flex gap-2"><x-ui.button variant="secondary" wire:click="resetVerification">Back</x-ui.button><x-ui.button wire:click="confirmTwoFactor">Confirm</x-ui.button></div></div>
@else<div class="mt-6 grid gap-5">@error('setupData')<p class="rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $message }}</p>@enderror@if($qrCodeSvg)<div class="mx-auto rounded-xl bg-white p-4">{!! $qrCodeSvg !!}</div>@endif@if($manualSetupKey)<label class="grid gap-2 text-sm font-semibold">Manual setup key<input readonly value="{{ $manualSetupKey }}" class="rounded-xl border border-slate-300 px-4 py-3 font-mono dark:bg-slate-800"></label>@endif<x-ui.button wire:click="showVerificationIfNecessary">Continue</x-ui.button></div>@endif
</div></div></section>
@endif

@if($canManagePasskeys)
<section class="mt-12 border-t border-slate-200 pt-8 dark:border-slate-700"><h3 class="text-lg font-bold">Passkeys</h3><p class="mt-1 text-sm text-slate-600 dark:text-slate-300">Manage your passkeys for passwordless sign-in</p>
<div class="my-6 overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-700">@forelse($passkeys as $passkey)<div class="flex items-center justify-between border-b border-slate-200 p-4 last:border-0 dark:border-slate-700"><div><p class="font-bold">{{ $passkey['name'] }}</p><p class="text-xs text-slate-500">Added {{ $passkey['created_at_diff'] }}</p></div><button type="button" wire:click="confirmDelete({{ $passkey['id'] }})" class="rounded-lg px-3 py-2 text-sm font-bold text-red-600 hover:bg-red-50">Remove</button></div>@empty<div class="p-8 text-center"><p class="font-bold">No passkeys yet</p><p class="mt-1 text-sm text-slate-500">Add a passkey to sign in without a password</p></div>@endforelse</div><x-passkey-registration/>
<div x-cloak x-show="$wire.showDeleteModal" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><div class="w-full max-w-md rounded-3xl bg-white p-6 dark:bg-slate-900"><h3 class="text-xl font-bold">Remove passkey</h3><p class="mt-2 text-sm">Remove “{{ $deletingPasskeyName }}” from your account?</p><div class="mt-6 flex justify-end gap-2"><x-ui.button variant="secondary" wire:click="closeDeleteModal">Cancel</x-ui.button><x-ui.button variant="danger" wire:click="deletePasskey">Remove passkey</x-ui.button></div></div></div>
</section>
@endif
</x-settings.layout></section>
