<?php

return [
    'shared' => [
        ['label' => 'Overview', 'icon' => 'fa-gauge-high', 'items' => [
            ['label' => 'Dashboard', 'icon' => 'fa-house', 'route' => 'dashboard'],
            ['label' => 'My activity', 'icon' => 'fa-clock-rotate-left', 'href' => '#'],
            ['label' => 'Notifications', 'icon' => 'fa-bell', 'href' => '#'],
            ['label' => 'Upcoming outreach', 'icon' => 'fa-calendar-check', 'route' => 'outreach'],
        ]],
        ['label' => 'My account', 'icon' => 'fa-circle-user', 'items' => [
            ['label' => 'My profile', 'icon' => 'fa-user-pen', 'route' => 'profile.edit'],
            ['label' => 'Participation role', 'icon' => 'fa-id-badge', 'route' => 'profile.edit'],
            ['label' => 'Role-change request', 'icon' => 'fa-right-left', 'route' => 'profile.edit'],
            ['label' => 'Account security', 'icon' => 'fa-shield-halved', 'route' => 'security.edit'],
            ['label' => 'Appearance', 'icon' => 'fa-palette', 'route' => 'appearance.edit'],
            ['label' => 'Help and support', 'icon' => 'fa-circle-question', 'route' => 'contact'],
        ]],
        ['label' => 'Explore Glow Health', 'icon' => 'fa-compass', 'items' => [
            ['label' => 'Services', 'icon' => 'fa-stethoscope', 'route' => 'services'],
            ['label' => 'Outreaches', 'icon' => 'fa-truck-medical', 'route' => 'outreach'],
            ['label' => 'Volunteer opportunities', 'icon' => 'fa-hand-holding-medical', 'route' => 'volunteer'],
            ['label' => 'Community impact', 'icon' => 'fa-chart-line', 'route' => 'impact'],
            ['label' => 'Contact Glow Health', 'icon' => 'fa-envelope', 'route' => 'contact'],
        ]],
    ],

    'roles' => [
        'community_member' => [
            ['label' => 'My healthcare', 'icon' => 'fa-heart-pulse', 'items' => [
                ['label' => 'Available services', 'icon' => 'fa-notes-medical', 'route' => 'services'],
                ['label' => 'Upcoming outreaches', 'icon' => 'fa-calendar-days', 'route' => 'outreach'],
                ['label' => 'Outreach eligibility', 'icon' => 'fa-circle-check', 'href' => '#'],
                ['label' => 'What to bring', 'icon' => 'fa-suitcase-medical', 'href' => '#'],
                ['label' => 'My registrations', 'icon' => 'fa-clipboard-list', 'href' => '#'],
                ['label' => 'Health information', 'icon' => 'fa-book-medical', 'href' => '#'],
                ['label' => 'Referral information', 'icon' => 'fa-share-from-square', 'href' => '#'],
            ]],
            ['label' => 'My participation', 'icon' => 'fa-person-circle-check', 'items' => [
                ['label' => 'Register for outreach', 'icon' => 'fa-pen-to-square', 'href' => '#'],
                ['label' => 'Registration status', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Saved outreaches', 'icon' => 'fa-bookmark', 'href' => '#'],
                ['label' => 'Give feedback', 'icon' => 'fa-comment-dots', 'href' => '#'],
                ['label' => 'Report a concern', 'icon' => 'fa-triangle-exclamation', 'href' => '#'],
            ]],
        ],
        'volunteer' => [
            ['label' => 'Volunteer workspace', 'icon' => 'fa-hand-holding-heart', 'items' => [
                ['label' => 'Available opportunities', 'icon' => 'fa-magnifying-glass', 'route' => 'volunteer'],
                ['label' => 'My applications', 'icon' => 'fa-file-lines', 'href' => '#'],
                ['label' => 'My assignments', 'icon' => 'fa-clipboard-check', 'href' => '#'],
                ['label' => 'Assigned tasks', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Availability', 'icon' => 'fa-calendar-plus', 'href' => '#'],
                ['label' => 'Volunteer profile', 'icon' => 'fa-address-card', 'route' => 'profile.edit'],
            ]],
            ['label' => 'Outreach operations', 'icon' => 'fa-truck-medical', 'items' => [
                ['label' => 'My outreach schedule', 'icon' => 'fa-calendar', 'href' => '#'],
                ['label' => 'Assigned location', 'icon' => 'fa-location-dot', 'href' => '#'],
                ['label' => 'Assigned team', 'icon' => 'fa-people-group', 'href' => '#'],
                ['label' => 'Check-in instructions', 'icon' => 'fa-right-to-bracket', 'href' => '#'],
                ['label' => 'Field responsibilities', 'icon' => 'fa-clipboard-list', 'href' => '#'],
                ['label' => 'Incident reporting', 'icon' => 'fa-triangle-exclamation', 'href' => '#'],
            ]],
            ['label' => 'Training and records', 'icon' => 'fa-graduation-cap', 'items' => [
                ['label' => 'Volunteer orientation', 'icon' => 'fa-person-chalkboard', 'href' => '#'],
                ['label' => 'Training materials', 'icon' => 'fa-book-open', 'href' => '#'],
                ['label' => 'Safety guidelines', 'icon' => 'fa-shield-heart', 'href' => '#'],
                ['label' => 'Attendance history', 'icon' => 'fa-clock-rotate-left', 'href' => '#'],
                ['label' => 'Volunteer hours', 'icon' => 'fa-clock', 'href' => '#'],
                ['label' => 'Certificates', 'icon' => 'fa-certificate', 'href' => '#'],
            ]],
        ],
        'healthcare_professional' => [
            ['label' => 'Clinical workspace', 'icon' => 'fa-user-doctor', 'items' => [
                ['label' => 'Clinical opportunities', 'icon' => 'fa-magnifying-glass', 'route' => 'volunteer'],
                ['label' => 'Credential verification', 'icon' => 'fa-id-card', 'href' => '#'],
                ['label' => 'Professional profile', 'icon' => 'fa-address-card', 'route' => 'profile.edit'],
                ['label' => 'Clinical assignments', 'icon' => 'fa-clipboard-check', 'href' => '#'],
                ['label' => 'Assigned tasks', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Availability', 'icon' => 'fa-calendar-plus', 'href' => '#'],
            ]],
            ['label' => 'Outreach care', 'icon' => 'fa-house-medical', 'items' => [
                ['label' => 'Clinical outreaches', 'icon' => 'fa-calendar-days', 'route' => 'outreach'],
                ['label' => 'Assigned care station', 'icon' => 'fa-bed-pulse', 'href' => '#'],
                ['label' => 'Clinical team', 'icon' => 'fa-user-group', 'href' => '#'],
                ['label' => 'Patient flow', 'icon' => 'fa-arrow-right-arrow-left', 'href' => '#'],
                ['label' => 'Referral pathways', 'icon' => 'fa-share-from-square', 'href' => '#'],
            ]],
            ['label' => 'Clinical resources', 'icon' => 'fa-book-medical', 'items' => [
                ['label' => 'Clinical protocols', 'icon' => 'fa-file-medical', 'href' => '#'],
                ['label' => 'Documentation guidelines', 'icon' => 'fa-clipboard', 'href' => '#'],
                ['label' => 'Medication controls', 'icon' => 'fa-pills', 'href' => '#'],
                ['label' => 'Infection prevention', 'icon' => 'fa-mask-face', 'href' => '#'],
                ['label' => 'Emergency procedures', 'icon' => 'fa-truck-medical', 'href' => '#'],
                ['label' => 'Clinical reports', 'icon' => 'fa-chart-column', 'href' => '#'],
            ]],
        ],
        'partner_sponsor' => [
            ['label' => 'Partnership workspace', 'icon' => 'fa-handshake', 'items' => [
                ['label' => 'Support opportunities', 'icon' => 'fa-lightbulb', 'route' => 'partner'],
                ['label' => 'Partnership proposals', 'icon' => 'fa-file-signature', 'href' => '#'],
                ['label' => 'My organisation', 'icon' => 'fa-building', 'href' => '#'],
                ['label' => 'Assigned tasks', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Partnership contacts', 'icon' => 'fa-address-book', 'href' => '#'],
            ]],
            ['label' => 'Contributions', 'icon' => 'fa-hand-holding-dollar', 'items' => [
                ['label' => 'Make a contribution', 'icon' => 'fa-circle-plus', 'href' => '#'],
                ['label' => 'Financial sponsorship', 'icon' => 'fa-money-bill-wave', 'href' => '#'],
                ['label' => 'Medical supplies', 'icon' => 'fa-kit-medical', 'href' => '#'],
                ['label' => 'Equipment support', 'icon' => 'fa-stethoscope', 'href' => '#'],
                ['label' => 'Logistics support', 'icon' => 'fa-truck', 'href' => '#'],
                ['label' => 'Contribution history', 'icon' => 'fa-clock-rotate-left', 'href' => '#'],
            ]],
            ['label' => 'Projects and impact', 'icon' => 'fa-chart-line', 'items' => [
                ['label' => 'Supported outreaches', 'icon' => 'fa-heart-circle-check', 'href' => '#'],
                ['label' => 'Project progress', 'icon' => 'fa-bars-progress', 'href' => '#'],
                ['label' => 'Impact reports', 'icon' => 'fa-file-chart-column', 'route' => 'impact'],
                ['label' => 'Agreements and documents', 'icon' => 'fa-folder-open', 'href' => '#'],
                ['label' => 'Accountability reports', 'icon' => 'fa-scale-balanced', 'href' => '#'],
            ]],
        ],
        'community_representative' => [
            ['label' => 'Community workspace', 'icon' => 'fa-people-roof', 'items' => [
                ['label' => 'Community profile', 'icon' => 'fa-map-location-dot', 'href' => '#'],
                ['label' => 'Community needs', 'icon' => 'fa-clipboard-question', 'href' => '#'],
                ['label' => 'Outreach requests', 'icon' => 'fa-paper-plane', 'href' => '#'],
                ['label' => 'Assigned tasks', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Community contacts', 'icon' => 'fa-address-book', 'href' => '#'],
            ]],
            ['label' => 'Outreach coordination', 'icon' => 'fa-people-arrows', 'items' => [
                ['label' => 'Submit outreach request', 'icon' => 'fa-circle-plus', 'href' => '#'],
                ['label' => 'Request status', 'icon' => 'fa-bars-progress', 'href' => '#'],
                ['label' => 'Venue preparation', 'icon' => 'fa-building-circle-check', 'href' => '#'],
                ['label' => 'Local mobilisation', 'icon' => 'fa-bullhorn', 'href' => '#'],
                ['label' => 'Accessibility planning', 'icon' => 'fa-universal-access', 'href' => '#'],
            ]],
            ['label' => 'Community reporting', 'icon' => 'fa-file-circle-check', 'items' => [
                ['label' => 'Health needs assessment', 'icon' => 'fa-notes-medical', 'href' => '#'],
                ['label' => 'Population information', 'icon' => 'fa-users', 'href' => '#'],
                ['label' => 'Priority health concerns', 'icon' => 'fa-heart-pulse', 'href' => '#'],
                ['label' => 'Vulnerable groups', 'icon' => 'fa-hands-holding-child', 'href' => '#'],
                ['label' => 'Post-outreach feedback', 'icon' => 'fa-comment-dots', 'href' => '#'],
            ]],
        ],
        'staff' => [
            ['label' => 'Operations', 'icon' => 'fa-gears', 'items' => [
                ['label' => 'Outreach calendar', 'icon' => 'fa-calendar-days', 'href' => '#'],
                ['label' => 'Outreach planning', 'icon' => 'fa-diagram-project', 'href' => '#'],
                ['label' => 'Field operations', 'icon' => 'fa-people-group', 'href' => '#'],
                ['label' => 'Assigned tasks', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Team schedule', 'icon' => 'fa-calendar-check', 'href' => '#'],
                ['label' => 'Venues and logistics', 'icon' => 'fa-truck', 'href' => '#'],
            ]],
            ['label' => 'People and outreach', 'icon' => 'fa-users-gear', 'items' => [
                ['label' => 'Community members', 'icon' => 'fa-users', 'href' => '#'],
                ['label' => 'Volunteers', 'icon' => 'fa-hand-holding-medical', 'href' => '#'],
                ['label' => 'Healthcare professionals', 'icon' => 'fa-user-doctor', 'href' => '#'],
                ['label' => 'Partners and sponsors', 'icon' => 'fa-handshake', 'href' => '#'],
                ['label' => 'Registration management', 'icon' => 'fa-clipboard-list', 'href' => '#'],
                ['label' => 'Inventory and supplies', 'icon' => 'fa-boxes-stacked', 'href' => '#'],
                ['label' => 'Incident reports', 'icon' => 'fa-triangle-exclamation', 'href' => '#'],
            ]],
            ['label' => 'Communication and reports', 'icon' => 'fa-chart-pie', 'items' => [
                ['label' => 'Announcements', 'icon' => 'fa-bullhorn', 'href' => '#'],
                ['label' => 'Participant messages', 'icon' => 'fa-comments', 'href' => '#'],
                ['label' => 'Outreach reports', 'icon' => 'fa-file-lines', 'href' => '#'],
                ['label' => 'Volunteer reports', 'icon' => 'fa-file-circle-check', 'href' => '#'],
                ['label' => 'Community impact', 'icon' => 'fa-chart-line', 'route' => 'impact'],
                ['label' => 'Export data', 'icon' => 'fa-file-export', 'href' => '#'],
            ]],
        ],
        'other' => [
            ['label' => 'Get started', 'icon' => 'fa-compass', 'items' => [
                ['label' => 'Describe my interest', 'icon' => 'fa-user-pen', 'route' => 'profile.edit'],
                ['label' => 'Participation pathways', 'icon' => 'fa-route', 'href' => '#'],
                ['label' => 'Recommended opportunities', 'icon' => 'fa-lightbulb', 'href' => '#'],
                ['label' => 'Assigned tasks', 'icon' => 'fa-list-check', 'href' => '#'],
                ['label' => 'Contact the team', 'icon' => 'fa-comments', 'route' => 'contact'],
            ]],
            ['label' => 'Explore opportunities', 'icon' => 'fa-binoculars', 'items' => [
                ['label' => 'Volunteer', 'icon' => 'fa-hand-holding-medical', 'route' => 'volunteer'],
                ['label' => 'Healthcare participation', 'icon' => 'fa-user-doctor', 'href' => '#'],
                ['label' => 'Community representation', 'icon' => 'fa-people-roof', 'href' => '#'],
                ['label' => 'Partnership and sponsorship', 'icon' => 'fa-handshake', 'route' => 'partner'],
                ['label' => 'Outreach attendance', 'icon' => 'fa-calendar-check', 'route' => 'outreach'],
            ]],
        ],
        'super_admin' => [
            ['label' => 'Control centre', 'icon' => 'fa-shield-halved', 'items' => [
                ['label' => 'Super-admin dashboard', 'icon' => 'fa-gauge-high', 'route' => 'admin.index'],
                ['label' => 'Platform overview', 'icon' => 'fa-chart-pie', 'href' => '#'],
                ['label' => 'Pending approvals', 'icon' => 'fa-hourglass-half', 'route' => 'admin.index'],
                ['label' => 'Administrative activity', 'icon' => 'fa-clock-rotate-left', 'href' => '#'],
            ]],
            ['label' => 'Users and access', 'icon' => 'fa-users-gear', 'items' => [
                ['label' => 'All users', 'icon' => 'fa-users', 'href' => '#'],
                ['label' => 'Community members', 'icon' => 'fa-house-user', 'href' => '#'],
                ['label' => 'Volunteers', 'icon' => 'fa-hand-holding-medical', 'href' => '#'],
                ['label' => 'Healthcare professionals', 'icon' => 'fa-user-doctor', 'href' => '#'],
                ['label' => 'Community representatives', 'icon' => 'fa-people-roof', 'href' => '#'],
                ['label' => 'Partners and sponsors', 'icon' => 'fa-handshake', 'href' => '#'],
                ['label' => 'Staff accounts', 'icon' => 'fa-id-badge', 'href' => '#'],
                ['label' => 'Role-change requests', 'icon' => 'fa-right-left', 'route' => 'admin.index'],
                ['label' => 'Roles and permissions', 'icon' => 'fa-key', 'href' => '#'],
                ['label' => 'Suspended accounts', 'icon' => 'fa-user-slash', 'href' => '#'],
            ]],
            ['label' => 'Task management', 'icon' => 'fa-list-check', 'items' => [
                ['label' => 'Delegate task', 'icon' => 'fa-paper-plane', 'route' => 'admin.index'],
                ['label' => 'All tasks', 'icon' => 'fa-list', 'href' => '#'],
                ['label' => 'Pending tasks', 'icon' => 'fa-clock', 'href' => '#'],
                ['label' => 'Completed tasks', 'icon' => 'fa-circle-check', 'href' => '#'],
                ['label' => 'Overdue tasks', 'icon' => 'fa-triangle-exclamation', 'href' => '#'],
                ['label' => 'Task reports', 'icon' => 'fa-chart-column', 'href' => '#'],
            ]],
            ['label' => 'Outreach management', 'icon' => 'fa-truck-medical', 'items' => [
                ['label' => 'All outreaches', 'icon' => 'fa-calendar-days', 'href' => '#'],
                ['label' => 'Create outreach', 'icon' => 'fa-circle-plus', 'href' => '#'],
                ['label' => 'Registrations', 'icon' => 'fa-clipboard-list', 'href' => '#'],
                ['label' => 'Teams and assignments', 'icon' => 'fa-people-group', 'href' => '#'],
                ['label' => 'Clinical stations', 'icon' => 'fa-house-medical', 'href' => '#'],
                ['label' => 'Venues and logistics', 'icon' => 'fa-truck', 'href' => '#'],
                ['label' => 'Inventory and supplies', 'icon' => 'fa-boxes-stacked', 'href' => '#'],
                ['label' => 'Referrals and incidents', 'icon' => 'fa-triangle-exclamation', 'href' => '#'],
            ]],
            ['label' => 'People programmes', 'icon' => 'fa-people-group', 'items' => [
                ['label' => 'Volunteer management', 'icon' => 'fa-hand-holding-heart', 'href' => '#'],
                ['label' => 'Credential approvals', 'icon' => 'fa-id-card', 'href' => '#'],
                ['label' => 'Clinical assignments', 'icon' => 'fa-stethoscope', 'href' => '#'],
                ['label' => 'Community requests', 'icon' => 'fa-people-roof', 'href' => '#'],
                ['label' => 'Needs assessments', 'icon' => 'fa-clipboard-question', 'href' => '#'],
                ['label' => 'Partner organisations', 'icon' => 'fa-building', 'href' => '#'],
                ['label' => 'Contributions', 'icon' => 'fa-hand-holding-dollar', 'href' => '#'],
            ]],
            ['label' => 'Communication', 'icon' => 'fa-bullhorn', 'items' => [
                ['label' => 'Announcements', 'icon' => 'fa-bullhorn', 'href' => '#'],
                ['label' => 'Notifications', 'icon' => 'fa-bell', 'href' => '#'],
                ['label' => 'Email campaigns', 'icon' => 'fa-envelope-open-text', 'href' => '#'],
                ['label' => 'SMS campaigns', 'icon' => 'fa-comment-sms', 'href' => '#'],
                ['label' => 'Message templates', 'icon' => 'fa-file-lines', 'href' => '#'],
                ['label' => 'Contact enquiries', 'icon' => 'fa-inbox', 'href' => '#'],
            ]],
            ['label' => 'Reports and content', 'icon' => 'fa-chart-line', 'items' => [
                ['label' => 'Platform analytics', 'icon' => 'fa-chart-pie', 'href' => '#'],
                ['label' => 'Outreach performance', 'icon' => 'fa-chart-column', 'href' => '#'],
                ['label' => 'Community impact', 'icon' => 'fa-chart-line', 'route' => 'impact'],
                ['label' => 'Export centre', 'icon' => 'fa-file-export', 'href' => '#'],
                ['label' => 'Public pages', 'icon' => 'fa-window-maximize', 'href' => '#'],
                ['label' => 'News and resources', 'icon' => 'fa-newspaper', 'href' => '#'],
                ['label' => 'Media library', 'icon' => 'fa-photo-film', 'href' => '#'],
            ]],
            ['label' => 'System administration', 'icon' => 'fa-sliders', 'items' => [
                ['label' => 'General settings', 'icon' => 'fa-gear', 'href' => '#'],
                ['label' => 'Navigation configuration', 'icon' => 'fa-bars', 'href' => '#'],
                ['label' => 'Account categories', 'icon' => 'fa-tags', 'href' => '#'],
                ['label' => 'Notification settings', 'icon' => 'fa-bell', 'href' => '#'],
                ['label' => 'Security settings', 'icon' => 'fa-shield-halved', 'href' => '#'],
                ['label' => 'Audit log', 'icon' => 'fa-scroll', 'href' => '#'],
                ['label' => 'System health', 'icon' => 'fa-heart-pulse', 'href' => '#'],
            ]],
        ],
    ],
];
